// Generated by gencpp from file crazyflie/AddCrazyflieResponse.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MESSAGE_ADDCRAZYFLIERESPONSE_H
#define CRAZYFLIE_MESSAGE_ADDCRAZYFLIERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crazyflie
{
template <class ContainerAllocator>
struct AddCrazyflieResponse_
{
  typedef AddCrazyflieResponse_<ContainerAllocator> Type;

  AddCrazyflieResponse_()
    {
    }
  AddCrazyflieResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddCrazyflieResponse_

typedef ::crazyflie::AddCrazyflieResponse_<std::allocator<void> > AddCrazyflieResponse;

typedef boost::shared_ptr< ::crazyflie::AddCrazyflieResponse > AddCrazyflieResponsePtr;
typedef boost::shared_ptr< ::crazyflie::AddCrazyflieResponse const> AddCrazyflieResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace crazyflie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::crazyflie::AddCrazyflieResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie/AddCrazyflieResponse";
  }

  static const char* value(const ::crazyflie::AddCrazyflieResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::crazyflie::AddCrazyflieResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddCrazyflieResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie::AddCrazyflieResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::crazyflie::AddCrazyflieResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_MESSAGE_ADDCRAZYFLIERESPONSE_H
