// Generated by gencpp from file crazyflie/AddCrazyflie.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MESSAGE_ADDCRAZYFLIE_H
#define CRAZYFLIE_MESSAGE_ADDCRAZYFLIE_H

#include <ros/service_traits.h>


#include <crazyflie/AddCrazyflieRequest.h>
#include <crazyflie/AddCrazyflieResponse.h>


namespace crazyflie
{

struct AddCrazyflie
{

typedef AddCrazyflieRequest Request;
typedef AddCrazyflieResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddCrazyflie
} // namespace crazyflie


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie::AddCrazyflie > {
  static const char* value()
  {
    return "5b59a3ab8b313e5f8ea146f7129a4bf5";
  }

  static const char* value(const ::crazyflie::AddCrazyflie&) { return value(); }
};

template<>
struct DataType< ::crazyflie::AddCrazyflie > {
  static const char* value()
  {
    return "crazyflie/AddCrazyflie";
  }

  static const char* value(const ::crazyflie::AddCrazyflie&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie::AddCrazyflieRequest> should match
// service_traits::MD5Sum< ::crazyflie::AddCrazyflie >
template<>
struct MD5Sum< ::crazyflie::AddCrazyflieRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie::AddCrazyflie >::value();
  }
  static const char* value(const ::crazyflie::AddCrazyflieRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie::AddCrazyflieRequest> should match
// service_traits::DataType< ::crazyflie::AddCrazyflie >
template<>
struct DataType< ::crazyflie::AddCrazyflieRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie::AddCrazyflie >::value();
  }
  static const char* value(const ::crazyflie::AddCrazyflieRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie::AddCrazyflieResponse> should match
// service_traits::MD5Sum< ::crazyflie::AddCrazyflie >
template<>
struct MD5Sum< ::crazyflie::AddCrazyflieResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie::AddCrazyflie >::value();
  }
  static const char* value(const ::crazyflie::AddCrazyflieResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie::AddCrazyflieResponse> should match
// service_traits::DataType< ::crazyflie::AddCrazyflie >
template<>
struct DataType< ::crazyflie::AddCrazyflieResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie::AddCrazyflie >::value();
  }
  static const char* value(const ::crazyflie::AddCrazyflieResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_MESSAGE_ADDCRAZYFLIE_H
