// Generated by gencpp from file crazyflie/Full.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MESSAGE_FULL_H
#define CRAZYFLIE_MESSAGE_FULL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>

namespace crazyflie
{
template <class ContainerAllocator>
struct Full_
{
  typedef Full_<ContainerAllocator> Type;

  Full_()
    : header()
    , twist1()
    , twist2()  {
    }
  Full_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , twist1(_alloc)
    , twist2(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist1_type;
  _twist1_type twist1;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist2_type;
  _twist2_type twist2;





  typedef boost::shared_ptr< ::crazyflie::Full_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie::Full_<ContainerAllocator> const> ConstPtr;

}; // struct Full_

typedef ::crazyflie::Full_<std::allocator<void> > Full;

typedef boost::shared_ptr< ::crazyflie::Full > FullPtr;
typedef boost::shared_ptr< ::crazyflie::Full const> FullConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie::Full_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie::Full_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazyflie::Full_<ContainerAllocator1> & lhs, const ::crazyflie::Full_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.twist1 == rhs.twist1 &&
    lhs.twist2 == rhs.twist2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazyflie::Full_<ContainerAllocator1> & lhs, const ::crazyflie::Full_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazyflie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyflie::Full_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie::Full_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie::Full_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie::Full_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie::Full_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie::Full_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie::Full_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6afbdb945f02d23afa7f796e1f4d470";
  }

  static const char* value(const ::crazyflie::Full_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6afbdb945f02d23ULL;
  static const uint64_t static_value2 = 0xafa7f796e1f4d470ULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie::Full_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie/Full";
  }

  static const char* value(const ::crazyflie::Full_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie::Full_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Twist twist1\n"
"geometry_msgs/Twist twist2\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::crazyflie::Full_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie::Full_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.twist1);
      stream.next(m.twist2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Full_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie::Full_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyflie::Full_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "twist1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist1);
    s << indent << "twist2: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_MESSAGE_FULL_H
