// Generated by gencpp from file crazyflie/UpdateParams.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MESSAGE_UPDATEPARAMS_H
#define CRAZYFLIE_MESSAGE_UPDATEPARAMS_H

#include <ros/service_traits.h>


#include <crazyflie/UpdateParamsRequest.h>
#include <crazyflie/UpdateParamsResponse.h>


namespace crazyflie
{

struct UpdateParams
{

typedef UpdateParamsRequest Request;
typedef UpdateParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateParams
} // namespace crazyflie


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crazyflie::UpdateParams > {
  static const char* value()
  {
    return "279e0627eb574ffe8968384218434f5f";
  }

  static const char* value(const ::crazyflie::UpdateParams&) { return value(); }
};

template<>
struct DataType< ::crazyflie::UpdateParams > {
  static const char* value()
  {
    return "crazyflie/UpdateParams";
  }

  static const char* value(const ::crazyflie::UpdateParams&) { return value(); }
};


// service_traits::MD5Sum< ::crazyflie::UpdateParamsRequest> should match
// service_traits::MD5Sum< ::crazyflie::UpdateParams >
template<>
struct MD5Sum< ::crazyflie::UpdateParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie::UpdateParams >::value();
  }
  static const char* value(const ::crazyflie::UpdateParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie::UpdateParamsRequest> should match
// service_traits::DataType< ::crazyflie::UpdateParams >
template<>
struct DataType< ::crazyflie::UpdateParamsRequest>
{
  static const char* value()
  {
    return DataType< ::crazyflie::UpdateParams >::value();
  }
  static const char* value(const ::crazyflie::UpdateParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crazyflie::UpdateParamsResponse> should match
// service_traits::MD5Sum< ::crazyflie::UpdateParams >
template<>
struct MD5Sum< ::crazyflie::UpdateParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crazyflie::UpdateParams >::value();
  }
  static const char* value(const ::crazyflie::UpdateParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crazyflie::UpdateParamsResponse> should match
// service_traits::DataType< ::crazyflie::UpdateParams >
template<>
struct DataType< ::crazyflie::UpdateParamsResponse>
{
  static const char* value()
  {
    return DataType< ::crazyflie::UpdateParams >::value();
  }
  static const char* value(const ::crazyflie::UpdateParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRAZYFLIE_MESSAGE_UPDATEPARAMS_H
