// Generated by gencpp from file crazyflie/UpdateParamsRequest.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MESSAGE_UPDATEPARAMSREQUEST_H
#define CRAZYFLIE_MESSAGE_UPDATEPARAMSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crazyflie
{
template <class ContainerAllocator>
struct UpdateParamsRequest_
{
  typedef UpdateParamsRequest_<ContainerAllocator> Type;

  UpdateParamsRequest_()
    : params()  {
    }
  UpdateParamsRequest_(const ContainerAllocator& _alloc)
    : params(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _params_type;
  _params_type params;





  typedef boost::shared_ptr< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateParamsRequest_

typedef ::crazyflie::UpdateParamsRequest_<std::allocator<void> > UpdateParamsRequest;

typedef boost::shared_ptr< ::crazyflie::UpdateParamsRequest > UpdateParamsRequestPtr;
typedef boost::shared_ptr< ::crazyflie::UpdateParamsRequest const> UpdateParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie::UpdateParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazyflie::UpdateParamsRequest_<ContainerAllocator1> & lhs, const ::crazyflie::UpdateParamsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.params == rhs.params;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazyflie::UpdateParamsRequest_<ContainerAllocator1> & lhs, const ::crazyflie::UpdateParamsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazyflie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "279e0627eb574ffe8968384218434f5f";
  }

  static const char* value(const ::crazyflie::UpdateParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x279e0627eb574ffeULL;
  static const uint64_t static_value2 = 0x8968384218434f5fULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie/UpdateParamsRequest";
  }

  static const char* value(const ::crazyflie::UpdateParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] params\n"
;
  }

  static const char* value(const ::crazyflie::UpdateParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie::UpdateParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyflie::UpdateParamsRequest_<ContainerAllocator>& v)
  {
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_MESSAGE_UPDATEPARAMSREQUEST_H
